### ISSUE TITLE
Had to create two aws vpn connections to connect to instances from each VPC

### ISSUE THREAD

**Issue by mar-io** [mboret/aws-vyos#1]
Thanks for the guide. I am a complete vyos noob. ran through all the steps but when the script is done and the vyos instance reboots nothing happens. There is no connection established to the aws vpn gateway. Is there any commands I should be running after the reboot or anything I should read up on?

**Comment by mar-io** [comment]
I got this working for some reason the script doesn't work for me. I had to go in and manually run the script in two parts. First, was the system image update. Then reboot. After the reboot I ran the individual commands. Configure. Run Commands. Commit. Save. Reboot. After the second reboot the connection was established. Thanks for the script though it is an extremely helpful push in the right direction.

**Comment by mar-io** [comment]
Another thing I noticed is that this didn't work for me both ways. I had to create a vpn connection in each vpc. I also had to create a vyos instance on each side. In your instructions you suggested adding the instance to the route table with the change source/dest disabled. Even after I did that the connections started from the EU vpc would not connect to the US instances.

**Comment by mboret** [comment]
Hi badmadrad,

Sorry for this late reply. One thing about the script, I think it doesn't work for you because I'd forgotten to said that before to run it you need to make it executable(chmod +x script.sh) and you need to be root(sudo su). 
I'll update the documentation. 

For your other question, I can confirm that this set up works. With only one Vyos instance you can have a working connection in the two sides.  

Typically for debugging, use icmp requests with a tcpdump open on the other instances(Before that, check the VPN status in the AWS VPC console, your tunnels must be "UP").
For example you have:
Instance1(in eu-west-1)  Vyos-Instance(in eu-west-1)  Instance2(in us-west-2)

Try to: 
1) ping Vyos-instance from Instance1 (if it doesn't work, check the security group of the Vyos Instance and the Instance1 route table(you must see the route to the Instance2 network)
2) ping the Instance2 from Instance1 and at the same time on your Vyos instance launch a tcp dump(tcpdump -f "icmp" -i eth0). If you see the icmp request, the problem should be come from the other side(us-west-1). 
3) ping the Vyos-Instance from the Instance2(if it doesn't work, check the security group of the Vyos Instance and the Instance2 route table(you must see the route to the Instance1 network)

I think it's a good start. Let me know if you still have the issue
